const CATEGORY_MAPPING_RULES = [
    {
        category: "Food",
        keywords: [
            "SWIGGY",
            "ZOMATO",
            "RESTAURANT",
            "CAFE",
            "DOMINOS",
            "MCDONALDS",
            "PIZZA",
            "FOOD",
            "EATS",
            "DUNZO",
            "BLINKIT",
            "ZEPTO",
        ],
    },
    {
        category: "Travelling",
        keywords: [
            "UBER",
            "OLA",
            "IRCTC",
            "MAKEMYTRIP",
            "GOIBIBO",
            "INDIGO",
            "SPICEJET",
            "AIRINDIA",
            "RAIL",
            "METRO",
            "PETROL",
            "FUEL",
        ],
    },
    {
        category: "Bill",
        keywords: [
            "ELECTRIC",
            "AIRTEL",
            "JIO",
            "VODAFONE",
            "BESCOM",
            "WATER",
            "GAS",
            "INSURANCE",
            "EMI",
            "NACH",
            "FINANCE LIMITED",
            "FINANCELIMITED",
            "L&T",
            "ACH D-",
            "RENT",
            "BILL",
        ],
    },
    {
        category: "Entertainment",
        keywords: [
            "NETFLIX",
            "SPOTIFY",
            "AMAZON PRIME",
            "HOTSTAR",
            "BOOKMYShow",
            "CINEMA",
            "GAME",
            "YOUTUBE",
        ],
    },
    {
        category: "Investment",
        keywords: [
            "ZERODHA",
            "GROWW",
            "MUTUAL",
            "SIP",
            "NSE",
            "BSE",
            "INVEST",
            "FD",
            "RD",
            "EBA",
            "EQ TRADE",
            "IDIRECT",
            "DIRECT TRXN",
        ],
    },
    {
        category: "Lend",
        keywords: ["LEND", "LOAN GIVEN", "P2P"],
    },
];

module.exports = { CATEGORY_MAPPING_RULES };
